### ISSUE TITLE
Incompatibility with Birb package manager

### ISSUE THREAD

**Issue by thatnerdjosh** [birb-linux/BirbOS#1]
Birb package manager seems to place packages in /tmp when building, but BirbOS has /tmp as noexec, so the configure script for packages can't run.

![Screenshot_debian11_2023-05-16_154136](https://github.com/Toasterbirb/BirbOS/assets/5251847/f29ba8a3-2c07-418a-995b-c5781d6f94ba)

**Comment by thatnerdjosh** [comment]
Probably more of a bug for the package manager, let me know if it should be there instead. `noexec` on /tmp is good practice afaik

**Comment by Toasterbirb** [comment]
Nice finding! That explains why I was able to install stuff in chroot but not when booted into BirbOS. Maybe there should be a separate tmpfs directory that is owned by a dedicated user and doesn't have the `noexec` flag.

**Comment by thatnerdjosh** [comment]
@Toasterbirb is this fixed?

**Comment by Toasterbirb** [comment]
No, this is still an issue. I'll make the build directory location customizable in the next update to `birb` and move it out from /tmp

**Comment by Toasterbirb** [comment]
Alrighty, the problem should be fixed now. If you want to use tmpfs with the package builds, mount the `/var/tmp/birb` directory as tmpfs in `/etc/fstab`
